(ns score.generators)

(defn- gen-util
  "Generator util that takes in two generator functions and standard function to 
  apply to values generated by generator functions"
  [func a b]
  (fn [t]
    (func (a t) (b t))))

(defn add-gen
  "Generator function that adds together the values from two other generators"
  [a b]
  (gen-util + a b))


(defn mul-gen
  "Generator function that adds together the values from two other generators"
  [a b]
  (gen-util * a b))
